//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        public int id { get; set; }
        public string username { get; set; }
        public string useremail { get; set; }
        public string userpass { get; set; }
        public Nullable<int> Profession { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneNumber2 { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> District { get; set; }
        public string Village { get; set; }
        public string image { get; set; }
        public string Description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
        public string Post { get; set; }
    }
}
